language: generic
sudo: required
dist: trusty
osx_image: xcode8

env:
  global:
    - LC_CTYPE=en_US.UTF-8

branches:
  only: 
    - master

matrix:
  include:
    - env: JOB=swiftpm_linux
      os: linux
      script:
        - swift build
        - SWIFT_PATH=`which swift` swift test

    - env: JOB=swiftpm_macos
      os: osx
      script:
        - swift build
        - swift test

    - env: JOB=xcode
      os: osx
      script:
        - swift build
        - swift package generate-xcodeproj
        - xcodebuild build-for-testing test-without-building -workspace SwiftRunner.xcworkspace -scheme SwiftRunner -sdk macosx -configuration Release -enableCodeCoverage YES ENABLE_TESTABILITY=YES | xcpretty

install:
  - if [ `uname` == "Linux" ] ; then 
      curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash ;
      . ~/.swiftenv/init;
      swiftenv install 3.0 || true;
    fi

after_success:
- |
  if [ "$JOB" == "xcode" ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
  sleep 10

notifications:
  email: false

