language: generic

env:
  global:
    - LC_CTYPE=en_US.UTF-8

branches:
  only: 
    - master

matrix:
  include:
    - env: JOB=swiftpm_linux
      os: linux
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build
        - swift test

    - env: JOB=swiftpm_macos
      os: osx
      script:
        - swift build
        - swift test

install:
  - if [ `uname` == "Linux" ] ; then 
    curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash ;
    fi

after_success:
- |
  if [ "$JOB" == "xcode_linux" ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
  sleep 10

notifications:
  email: false

